"""add resource assigned_user_id

Revision ID: b9ab06b5b1b5
Revises: 951fb25b680b
Create Date: 2026-09-19 04:57:42.058279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b9ab06b5b1b5'
down_revision: Union[str, None] = '951fb25b680b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_units', sa.Column('assigned_user_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'resource_units', 'users', ['assigned_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resource_units', type_='foreignkey')
    op.drop_column('resource_units', 'assigned_user_id')
    # ### end Alembic commands ###
